### ISSUE TITLE
PlayerJoinEvent

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#232] opened 2015-05-24 21:47 UTC
playerjoinEvent is causing lag, can you look into it?

![vnxizor](https://cloud.githubusercontent.com/assets/9636316/7789846/9da7d3ac-0224-11e5-9121-4015ca6f262a.png)

@drtshock

**Comment by Lotteries** [comment] 2015-05-26 14:24
I'm currently in class @Doxify I will grab a timings report during my peak players and see what my timings says after i get home in about 50minutes. I will post back once i get them.

**Comment by MoeXIV** [comment] 2015-05-26 16:07
It's the fact you have so many players doing so many things. There is easily 100 people constantly trying to join / leave as well as the fact it has to listen for player deaths to update DTR. 

My assumption is that there's just to much going on, and to much for the server to do. Maybe try to get a core implanted with 5 or 6 plugins in 1 to reduce the need of CPU usage with all the different plugins running at the same time. 

swag

**Comment by Doxify** [comment] 2015-05-26 18:01
Just started running on an overclocked i7 4790k so performance has improved a lot but I'll talk to my dev about a "core" plugin.

**Comment by nsporillo** [comment] 2015-06-06 03:24
Despite being the first issue, going to mark this duplicate of #247

**Closed by nsporillo** 2015-06-06 03:24 UTC
Labels: duplicate
