### ISSUE TITLE
Ally bug?

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#90] opened 2015-03-30 19:20 UTC
This fac exceeded allies:

http://i.imgur.com/YaIz0vL.png

**Comment by nsporillo** [comment] 2015-03-30 19:46
Duplicate of #24 

That issue was closed, but I re-opened it as I did confirm this a few days ago.

This was a bug present in the upstream factions (factionsuuid) as well. It happens when multiple ally requests are sent before reaching the limit, and then accepting them.. allows bypass.

**Closed by nsporillo** 2015-03-30 19:46 UTC
