### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by iOxf** [drtshock/HCFProblems#380] opened 2016-01-19 20:53 UTC
Anyone can help me? 
to do this.
http://prntscr.com/9s8zkj
The owner, type me what the messages, is editable in lang.yml, but i try this and i get this result:
http://prntscr.com/9s9095
I have a space in Leaving, If anyone can help me. please :)

**Comment by Manehh** [comment] 2016-01-19 22:54
Remove the space?

**Comment by nsporillo** [comment] 2016-01-20 18:15
Post your lang.yml into a [gist](https://gist.github.com) and link it here. Perhaps could figure out what the issue is.

**Comment by iOxf** [comment] 2016-01-21 20:23
https://gist.github.com/iOxf/eda9cd0e2131b33d38e1

**Comment by nsporillo** [comment] 2016-01-22 16:52
On this line:
`faction-leave: <i>Entering %2$s&e(&cDeathban&e)                        Leaving %1$s&e(&cDeathban&e)`

You just have to get the right amount of spaces with trial and error I'm guessing. I don't think there is currently a symbol in the plugin which will force a line break, although there probably should be.

**Comment by iOxf** [comment] 2016-01-23 19:17
I'll try this:
faction-leave: '&e Now Entering: %2$s&e(&cDeathban&e)                                 Now
  Leaving: %1$s&e(&cDeathban&e)'
And get this result: http://prntscr.com/9tvuxw
I have a space. xD, but i remove the space and get this result: http://prntscr.com/9tvvh0

**Comment by MoeXIV** [comment] 2016-01-25 13:59
Just use YAML line splitting....

faction-leave: |-
  line 1
  line 2
  line 3

**Comment by MoeXIV** [comment] 2016-01-25 13:59
Keep in mind spacing won't be too accurate because I'm on my phone but the lines go 2 spaces after the beginning of faction-leave

**Comment by iOxf** [comment] 2016-01-26 03:32
I think add a update of this
like:
faction-entering: Now Entering: %faction%
faction-leave: Now Leaving: %faction%

**Comment by nsporillo** [comment] 2016-02-02 05:28
Closing this, will move discussion to a new issue here  -> #389

**Closed by nsporillo** 2016-02-02 05:28 UTC
