### ISSUE TITLE
Warning on PlayerJoinEvent - Related to Scoreboard?

### ISSUE THREAD

**Issue by DirtHunter** [drtshock/HCFProblems#379] opened 2016-01-18 19:13 UTC
Hi,

I am getting the following error on HCFactions plugin I bought yesterday: https://gyazo.com/7f5e9101e04374a413671fc0465b78d2 I thought this was an issue with the HCF Stuff plugin I have but it works fine without HCFactions.

From what I can see it seems like it's something to do with the scoreboards conflicting so I tried to remove the scoreboard by changing the following in the config:

default-enabled: false
expiration: 0
default-prefixes: false

Sorry, if I have missed anything I have checked other bug reports relating to scoreboards but couldn't find anything.

Thanks for any help in advance!

**Comment by nsporillo** [comment] 2016-01-18 19:57
This issue is an duplicate of https://github.com/drtshock/HCFProblems/issues/368

Read more there, if you need access to the CI - register and email me your username. (I also need to verify you purchased on MCExchange).

**Closed by nsporillo** 2016-01-18 19:57 UTC
