### ISSUE TITLE
./f show (no fac)

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#76] opened 2015-03-27 23:34 UTC
When your not in a fac and you do /f show then it replies with nothing.

Not even a blank input.

**Comment by nsporillo** [comment] 2015-03-27 23:48
Duplicate of https://github.com/drtshock/HCFProblems/issues/74

**Comment by TMNetwork** [comment] 2015-03-27 23:50
@nsporillo you closed the last one....

**Comment by Doxify** [comment] 2015-03-27 23:52
which means it's either going to be fixed or its already fixed, he already knows about the issue, making another thread won't fix anything.

**Comment by nsporillo** [comment] 2015-03-28 00:02
Latest build resolves this.

**Closed by nsporillo** 2015-03-28 00:02 UTC
Labels: duplicate
