### ISSUE TITLE
Wilderness  enemy 

### ISSUE THREAD

**Issue by EnzoCARP** [drtshock/HCFProblems#218] opened 2015-05-15 15:42 UTC
Wilderness areas in claimeadas by you can not put / f  home as enemy

**Comment by EnzoCARP** [comment] 2015-05-15 16:00
I am told is a feature as the off?

**Comment by EnzoCARP** [comment] 2015-05-15 16:00
Wilderness is not the enemy and the other factions if

**Comment by EnzoCARP** [comment] 2015-05-15 16:04
Nick: Starwerty mcexchange.

**Comment by drtshock** [comment] 2015-05-15 17:21
what

**Comment by Lotteries** [comment] 2015-05-15 17:23
@drtshock @EnzoCARP wat

**Comment by Lotteries** [comment] 2015-05-15 17:24
@EnzoCARP  Could you try to explain in some readable English? As far as i can see, this looks like Chinese to me.

**Comment by MoeXIV** [comment] 2015-05-15 17:31
I wouldn't recommend making fun of someone's attempt at speaking a non native language. He's clearly trying to use some sort of translator, that doesn't seem to be working in his favor. 

It's like me trying to translate English into Chinese. It will make 0 sense.

**Comment by Lotteries** [comment] 2015-05-15 17:37
Ah, i think i get what you're trying to say. Are you TRYING to say that you don't want people in the wilderness (default) faction to be able to pvp?

**Comment by nsporillo** [comment] 2015-05-27 06:41
@EnzoCARP gonna close this as there has been no reply in a week and we cannot understand what the issue is.

**Closed by nsporillo** 2015-05-27 06:41 UTC
