### ISSUE TITLE
HCF /f show problem

### ISSUE THREAD

**Issue by bigbubba69** [drtshock/HCFProblems#196] opened 2015-05-09 14:49 UTC
I am getting an internal error while doing /f show
http://prntscr.com/73adua

**Comment by KriticalPvP** [comment] 2015-05-09 15:08
@bigbubba69 I have been getting this error too, However I fixed it. /f disband. & /f create (name) You need to re-create the faction. Hope this helped!

**Comment by drtshock** [comment] 2015-05-09 20:26
What's the error? And what's your username on the CI so I can confirm you purchased this?

**Comment by Lilmac12312** [comment] 2015-05-09 21:56
Instead of disbanding the faction and re-creating it why don't you check the console for any logs and post them in a file so the developers can find the issue?

**Comment by KriticalPvP** [comment] 2015-05-10 10:34
@Lilmac12312 I'm not saying do that for a permanent fix, but for short term.

**Comment by nsporillo** [comment] 2015-05-13 02:43
Closing this because we cannot confirm if @bigbubba69 has a license or not.

**Closed by nsporillo** 2015-05-13 02:43 UTC
Labels: no license
