### ISSUE TITLE
Ally Bug still persists

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#105] opened 2015-04-03 23:18 UTC
Nick knows about this bug....
but it still works...
http://i.imgur.com/8COTBwm.png
and there is an extra space between Allies:  {ALLIES}

**Comment by NauruMC** [comment] 2015-04-04 00:33
Simple fix, go to config yml and make somthing like this

Allies:{ALLIES} no space, i had the same issue and i fixed it using that, 
that is a temp. fix until he comes out with a real fix.

**Comment by TMNetwork** [comment] 2015-04-04 01:38
@NauruMC there is still an extra space
http://gyazo.com/f78c11b95975c8200f183bde4a58dc59

**Comment by nsporillo** [comment] 2015-04-07 18:20
What exactly is the issue here?

That there is an extra space? Or that you can still get 3 allies if the max is 2?

Please stop addressing different issues with the same post, it's not only harder to understand but you force seperate fixes to close one issue. It doesnt make sense. 

If factions can still exceed 3 allies, edit your original issue that is closed and update it with useful information. Show how to replicate the issue.

You do yourself a disservice by ignoring what we ask... Continually explain to you to stop making duplicate issues as it clutters the tracker and spreads out information everywhere. 

This will be closed because it is a duplicate of the closed ticket that you need to update (and then I will open it). The 2nd portion of this issue is an issue with your configuration and if not, do not make a new issue because changes were already made (but a new build was not pushed yet) that probably fix it.

**Closed by nsporillo** 2015-04-07 18:20 UTC

**Comment by TMNetwork** [comment] 2015-04-07 21:18
Update as you wish:
You can still exceed 3 allies and I'll open another ticket about the extra
space on the allies portion.
