### ISSUE TITLE
More than the set amount of allies

### ISSUE THREAD

**Issue by Lilmac12312** [drtshock/HCFProblems#129] opened 2015-04-18 01:59 UTC
Not sure how it happened but I've set the max allies as 1 yet this faction has two: http://prntscr.com/6v2s4j

**Comment by LOOOOOOOL** [comment] 2015-04-18 02:53
yea this bug continues to happen with me too, but im not on the updated version yet.

**Comment by MoeXIV** [comment] 2015-04-18 03:17
They may have allied 2 people before the 1 ally was put in the plugin?

**Comment by Lilmac12312** [comment] 2015-04-18 05:44
@MoeXIV allies were set to only one before the server release.

**Comment by LOOOOOOOL** [comment] 2015-04-19 01:20
LOL @Lilmac12312 got no license. How about your cheap ass pays for the plugin rather than asking others for free dl links ?

**Comment by Lilmac12312** [comment] 2015-04-19 02:01
@LOOOOOOOL I'm not "asking" or "getting" any download links. @MoeXIV and I run a Network together, Moe paid for the plugin and runs all the servers but is currently away for 2-3 days as he's at his cottage with family. He asked me to maintain and look after the server, all I'm doing is posting errors within the plugin so they can be fixed for those who have purchased the plugin, including Moe so the servers run smooth.

**Comment by MoeXIV** [comment] 2015-04-19 02:04
Thank you, Lilmac. I was about to comment some "rage". Lilmac basically read my mind. We run the network as a team of individuals, no need to call him "cheap". :>

**Comment by nsporillo** [comment] 2015-04-19 21:00
Regardless, the primary objective of the license in our case is for providing support. Without a license, I won't be providing support. 

https://github.com/drtshock/HCFProblems/issues/127#issuecomment-94046074

**Comment by Lilmac12312** [comment] 2015-04-20 03:45
@nsporillo Well if @MoeXIV was to submit all issues would he then be provided with support as he holds the license.

**Comment by nsporillo** [comment] 2015-04-20 03:55
@Lilmac12312 technically yeah, but technically that cant kill any motivation to work on the project if our hard work is countered by circumventing our licensing. 135 issues on this tracker in less than 2 months. Many of which were resolved in a short window. @drtshock already outlined that a license is per instance. If you'd like support, we ask you purchase a license.

**Comment by Lilmac12312** [comment] 2015-04-20 04:38
@nsporillo I'll purchase a license then :)

**Comment by nsporillo** [comment] 2015-04-20 14:59
Re-opening this. Just confirmed it is still a bug. 

Turns out there is several cases in which we must have checks. 

If you have 1 ally and sent out an ally request to some faction and then get sent an ally request from another. You can exceed the limit, but only by 1. 

I'll work on a fix. But personally quirks like this in plugins is sometimes a neat thing for users.. easter-egg-esque. Oh well, thanks for reporting. I'll work up a fix.

**Comment by Lilmac12312** [comment] 2015-04-20 22:23
Basically the way it works is:

If a faction has max allies, say in the config it's set to having 1 max ally and another faction has no allies they can send you an ally request and you're able to accept as they don't have any allies

**Closed** 2015-04-21 23:51 UTC
Labels: bug, in progress
