### ISSUE TITLE
Subclaims

### ISSUE THREAD

**Issue by HeyImYellow** [drtshock/HCFProblems#230] opened 2015-05-21 22:55 UTC
So basically what Subclaims are is that when you place a sign on a chest with the top line being 

[Subclaim]
Username
Username
Username

It will only allow people who have their name included on the sign under the [Subclaim] line. For example:

[Subclaim]
HeyImYellow
NSPorillo

This will only allow me and NSPorrillo to open that chest (Except if you are raid able!)

Would be nice to add this :)

**Comment by SaiCoFlu** [comment] 2015-05-21 23:33
Already been requested I'm pretty sure.

**Comment by Lotteries** [comment] 2015-05-22 13:53
It has been already requested, duplicate of #137. The feature has been put on hold.

**Comment by drtshock** [comment] 2015-05-22 14:40
This is a bit different as I believe he's talking about player owned chunks though I thought that was already possible.

**Comment by Lotteries** [comment] 2015-05-22 14:53
Nope, subclaims are expressed as chests. I know it sounds wierd with the name 'Sub claims' but that is how it is on HCTeams.com *Shameless advertisement*

**Comment by HeyImYellow** [comment] 2015-05-22 18:39
No this is different as that one suggests a "MOD" chest where only Faction Moderators can use them.

This is a player based one where ANY player can create a chest subclaim to keep THEIR goods safe, not just faction moderators.

**Comment by nsporillo** [comment] 2015-05-27 06:48
@HeyImYellow doesn't this almost spoil the idea of a faction? How are you banded together if people will just private their chests within the faction. I think it changes the gameplay and adds a bit of complexity to the plugin without much justification.

Faction mod chests is not only much more feasible to implement in a timely manner, but makes sense. `Faction mods should be trusted to handle secure items to prevent insiding.`

What happens when you invite a player and they move their stuff to your faction and protect their chest under the notion it's safe, and you just kick them out.. what happens then? do we need to keep those chests safe for the protect owner or let the faction reclaim them? This request just adds too many side effects to jump in and add, especially without *enough* justification. 

Hope this spurs some discussion.

**Comment by Lotteries** [comment] 2015-06-02 14:03
@HeyImYellow @nsporillo I don't this should be added. As Nick stated, it ruins the gamemode. Everyone wants this plugin to be more like HCTeams, but HCTeams is a COMPLETELY different gamemode then HCFactions.

**Comment by nsporillo** [comment] 2015-06-06 03:28
@Lotteries things shouldn't be added just to be added if they don't belong. Making them configurable doesnt un-do the added complexity and the other implications of more code.

**Closed by nsporillo** 2015-06-06 03:28 UTC
Labels: needs justification
