### ISSUE TITLE
Chat Prefix Removal

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#67] opened 2015-03-27 00:00 UTC
Can you make this be able to be removed from public chat?
http://gyazo.com/ee5b72a028f0285baa7366d0d3d278ce

The prefixes are mean't for only /f show in HCF. If you want, you can make it configurable in case others prefer it.

**Comment by nsporillo** [comment] 2015-03-27 00:01
Duplicate of https://github.com/drtshock/HCFProblems/issues/36.

**Closed by nsporillo** 2015-03-27 00:01 UTC
