### ISSUE TITLE
Access To CI

### ISSUE THREAD

**Issue by nscwalk** [drtshock/HCFProblems#8] opened 2015-03-14 08:40 UTC
Can I  get granted access to The CI build for this plugin?? I have already bought it I just want the 0.0.4 version

**Comment by Doxify** [comment] 2015-03-14 16:06
Same here, I need access to the latest version. I skyped and emailed trent with no response.

**Comment by drtshock** [comment] 2015-03-14 18:16
We currently don't have any new builds to distribute. We're working on a new site and we will release that once we are ready. Making this a duplicate of #5.

**Closed by drtshock** 2015-03-14 18:16 UTC
