### ISSUE TITLE
Leaving wilderness

### ISSUE THREAD

**Issue by youngpvprock** [drtshock/HCFProblems#201] opened 2015-05-10 00:43 UTC
There are messages from:
Leaving safezone, Entering Warzone
Leaving Warzone Entering Wilderness
Leaving <faction> entering Wilderness
but the message from Leaving Wildernes Entering <Faction> does not exist, can add it please?

**Comment by nsporillo** [comment] 2015-05-10 00:46
what?

**Comment by AlfieC** [comment] 2015-05-10 12:02
He's saying that lang.yml does not allow for the customisation of the 'leaving wilderness' message.

**Comment by youngpvprock** [comment] 2015-05-10 15:40
Leaving wilderness Entering <Faction> doesn't exist.. Just exist Leaving <Faction> Entering Wilderness

**Comment by nsporillo** [comment] 2015-05-11 01:25
@youngpvprock what is your username on the Jenkins so I can confirm you've purchased the plugin?

**Comment by youngpvprock** [comment] 2015-05-11 12:33
@nsporillo ->Cazmon

**Comment by nsporillo** [comment] 2015-05-11 13:58
@youngpvprock thank you.

You're looking for the TL in lang.yml:

    faction-leave: <a>Leaving %1$s, <a>Entering %2$s

on line 669.

**Comment by youngpvprock** [comment] 2015-05-11 14:19
@nsporillo I'll rec a video, i think you aren't understand what i'm trying to say, i can't explain better because english isn't my main lang

**Comment by youngpvprock** [comment] 2015-05-11 16:21
@nsporillo  Check video, you will see in last part of video, never Appear the message when entering a faction claim, just leaving
https://www.youtube.com/watch?edit=vd&v=vsxAg_l31ZU

**Comment by nsporillo** [comment] 2015-05-11 22:37
![uhm](http://puu.sh/hJVCf/2009a33216.png)

Appears to work fine with default configuration. Not sure what is going wrong.

**Comment by youngpvprock** [comment] 2015-05-11 23:26
Plugin has debug? So i paste what happen, it's a strange bug.

**Comment by nsporillo** [comment] 2015-05-13 13:59
This seems to be working fine despite the video evidence that is not for @youngpvprock , going to need more info otherwise going to close this issue :panda_face:

**Comment by nsporillo** [comment] 2015-05-27 17:30
closing this, @youngpvprock hasn't gotten back in 2 weeks and was not able to confirm the issue...

**Closed by nsporillo** 2015-05-27 17:30 UTC
Labels: needs more info
