### ISSUE TITLE
f Stuck

### ISSUE THREAD

**Issue by LOOOOOOOL** [drtshock/HCFProblems#130] opened 2015-04-18 02:50 UTC
Can you make it where if you walk more than 5 blocks in f stuck then it cancel's your tp?

**Comment by nsporillo** [comment] 2015-04-18 07:33
Why do you consistently open issues for the same exact issue that has been solved.
Duplicate of https://github.com/drtshock/HCFProblems/issues/107

    hcf.fstuck.radius 

...in config.yml.

If you're not running a build that has this feature, then I have to ask why you request features and then not upgrade to get them, then continue to make issues. I can't just add content to and old file you're running. Stay updated if you want new features.

**Closed by nsporillo** 2015-04-18 07:33 UTC

**Comment by LOOOOOOOL** [comment] 2015-04-18 20:41
@nsporillo DUDE OK. WHERE TEH FUCK DO I ASK QUESTIONS THEN? I DONT WANNA UPGRADE AND HAVE ISSUES. GIVE ME A CORRECT PLACE TO ASK QUESTIONS. I DONT FOLLOW THIS DAMN GIT 24/7 AND TRENT TOLD ME VIA SKYPE TO ASK QUESTIONS ON THE GIT.

**Comment by nsporillo** [comment] 2015-04-18 22:49
1) Git is the right place to ask questions. Your question was **answered** and then **closed**. What else is there do it?

2) If you request a feature, but don't want to upgrade to the build that **has** the requested feature, then that's just too bad, nothing I can do. But don't make new tickets about issues that are **resolved** because you can't read the upgrade document through. It says you'll have issues if you don't switch to a new config.yml, just read the document it isn't rocket science. 

3) You don't need to follow the issues tracker 24/7 to **see that you're own** issues have been solved. Taking 5 minutes to read saves you the time of writing your message and waiting for a response to continue. It also saves me the time of writing out blocks of paragraphs.
